version: '3.7'

services:
  caddy:
    image: technoguyfication/caddy-cloudflare:alpine
    container_name: caddy
    restart: unless-stopped
    environment:
      - ACME_EMAIL=$ACME_EMAIL
      - CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN
      - ACME_AGREE=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data:/data
      - ./config:/config

networks:
  default:
    external:
      name: caddy
