version: '3'

services:
  bitwarden:
    image: vaultwarden/server
    container_name: bitwarden
    hostname: bitwarden
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true
      - WEB_VAULT_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=123456789
    volumes:
      - ./data:/data

networks:
  default:
    external:
      name: caddy
