version: '3'

services:
  bitwarden:
    image: vaultwarden/server
    container_name: bitwarden
    hostname: bitwarden
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/data

networks:
  default:
    external:
      name: caddy
